### ISSUE TITLE
Some suggested adjustments:

### ISSUE THREAD

**Issue by Falke-Design** [haelue/Leaflet.StarCircle#1]
1. Copy & Paste error - wrong function name:
https://github.com/haelue/Leaflet.StarCircle/blob/242553c36275a3a28cfec7514846e0a7f90892e4/src/leaflet-starcircle.js#L103

2. I strongly suggest to extend `L.Circle` and creating a own shape `L.StarCircle` instead of including the option and overwriting functions. If Leaflet changes some internal logic for example in `initialize`, you need always to update your code else you will overwrite it with your code and revert it to the old version.  

```
L.StarCircle = L.Circle.extend({
  initialize: function (latlng, options, legacyOptions) {
    L.Circle.prototype.initialize.call(this, latlng, options, legacyOptions);
    this._star = this.options.star;
  },

  // @method setStar(star: Number): this
  // Sets the n-star of a star-marker.
  setStar: function (star) {
    this._star = star;
    return this.redraw();
  },

  // @method getStar(): Number
  // Returns the current n-star of a star-marker.
  getStar: function () {
    return this._star;
  },
});
```

3. Update to new Leaflet Version
https://github.com/haelue/Leaflet.StarCircle/blob/242553c36275a3a28cfec7514846e0a7f90892e4/index.html#L7-L8

4. Use the same name everywhere
![grafik](https://user-images.githubusercontent.com/19800037/220293150-1ff823ec-a637-438a-a1e7-cbbd83e0c359.png)

5. Enable Github-Pages in the setting, then the demo can be visited over https://haelue.github.io/Leaflet.StarCircle/index.html

**Comment by haelue** [comment]
All modified as your wish!
